# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)
    projects: '**/ToDoApp.Api.csproj'
    arguments: '--output $(build.artifactstagingdirectory)\api --configuration Release'
   

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/ToDoApp.Api.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)
    projects: '**/ToDoApp.UI.csproj'
    arguments: '--output $(build.artifactstagingdirectory)\ui --configuration Release'


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)\api'
    artifact: 'api'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
   targetPath: '$(build.artifactstagingdirectory)\ui'
   artifact: 'web'
   publishLocation: 'pipeline'